namespace ezBot
{
    interface ITranslator
    {
        string EzBot { get; }
        string By { get; }
        string Version { get; }
        string Support { get; }
        string Garena { get; }
        string SourceCode { get; }
        string Issues { get; }
        string AdministratorRequired { get; }
        string ConfigLoaded { get; }
        string LauncherPathInvalid { get; }
        string PleaseTryThis { get; }
        string LauncherFix1 { get; }
        string LauncherFix2 { get; }
        string LauncherFix3 { get; }
        string LauncherFix4 { get; }
        string LauncherFix5 { get; }
        string ChangingGameConfig { get; }
        string LoadingAccounts { get; }
        string MaximumBotsRunning { get; }
        string YouMayHaveAnIssueInAccountsFile { get; }
        string AccountsStructure { get; }
        string ErrorGetGarenaToken { get; }
        string ErrorLeagueGameCfgRegular { get; }
        string ErrorLeagueGameCfgGarena { get; }
        string NoMoreAccountsToLogin { get; }
        string GameModeInvalid { get; }
        string WillShutdownOnceCurrentMatchEnds { get; }
        string EzBotGameStatus { get; }
        string AcceptingLobbyInvite { get; }
        string AllPlayersAccepted { get; }
        string PlayersAcceptedCount { get; }
        string EnteringChampionSelect { get; }
        string YouAreInChampionSelect { get; }
        string SelectedChampion { get; }
        string WaitingForOtherPlayersLockin { get; }
        string ChampionNotAvailable { get; }
        string WaitingChampSelectTimer { get; }
        string YouAreInQueue { get; }
        string ReQueued { get; }
        string QueuePopped { get; }
        string AcceptedQueue { get; }
        string YouHaveLeaverBuster { get; }
        string LaunchingLeagueOfLegends { get; }
        string ClosingGameClient { get; }
        string InQueueAs { get; }
        string QueueFailedReason { get; }
        string LeaverBusterTaintedWarningError { get; }
        string WaitingDodgeTimer { get; }
        string WaitingLeaverTimer { get; }
        string JoinedLowPriorityQueue { get; }
        string ErrorJoiningLowPriorityQueue { get; }
        string ErrorOccured { get; }
        string RestartingLeagueOfLegends { get; }
        string RestartingLeagueOfLegendsAt { get; }
        string PositionInLoginQueue { get; }
        string LoggingIntoAccount { get; }
        string SummonerDoesntExist { get; }
        string CreatingSummoner { get; }
        string CreatedSummoner { get; }
        string AlreadyMaxLevel { get; }
        string LogIntoNewAccount { get; }
        string BuyingXpBoost { get; }
        string CouldntBuyBoost { get; }
        string Normal5Requirements { get; }
        string JoinCoopBeginnerUntil { get; }
        string NeedLevel6BeforeAram { get; }
        string NeedLevel7Before3v3 { get; }
        string Welcome { get; }
        string SendingGameInvites { get; }
        string WaitingGameInviteFrom { get; }
        string LevelUp { get; }
        string CurrentRp { get; }
        string CurrentIp { get; }
        string CharacterReachedMaxLevel { get; }
        string DownloadingMasteries { get; }
        string UpdatingMasteries { get; }
        string Disconnected { get; }
        string BoughtXpBoost3Days { get; }
    }
}
